# Generated by Django 3.2.3 on 2021-05-31 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npo_user', '0003_alter_npouser_email'),
        ('npo_icnl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICNLFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icnl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='npo_icnl.icnl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved2', to='npo_user.npouser')),
            ],
        ),
    ]
