# Generated by Django 3.2.3 on 2021-05-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npo_user', '0002_alter_npouser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npouser',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='email'),
        ),
    ]
