# Generated by Django 3.2.3 on 2021-05-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npo_user', '0002_alter_npouser_managers'),
        ('npo_news', '0002_newsfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfavorite',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='npo_user.npouser'),
        ),
    ]
