# Generated by Django 3.2.3 on 2021-05-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npo_user', '0002_alter_npouser_managers'),
        ('npo_publication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='npo_publication.publication')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkbox', to='npo_user.npouser')),
            ],
        ),
    ]
